# -*- coding: utf-8 -*-
"""NVDA_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Qq5G9yQEo4q5u2mbGzU7Cu1bOiwo6LI

# EDA - NVDA Stock Price

## 1. Setup inicial
"""

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive

drive.mount('/content/drive')

DATA_PATH = Path("/content/drive/MyDrive/NVDA (3).csv")

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)

sns.set_theme(style="whitegrid", context="notebook")
plt.rcParams["figure.figsize"] = (12, 5)
plt.rcParams["axes.titleweight"] = "bold"

"""## 2. Carga del dataset

"""

if not DATA_PATH.exists():
    raise FileNotFoundError(f"No se encontró el archivo: {DATA_PATH.resolve()}")

df_raw = pd.read_csv(DATA_PATH)
df = df_raw.copy()

print(f"Filas: {df.shape[0]:,}")
print(f"Columnas: {df.shape[1]:,}")
display(df.head())
display(df.tail())

"""## 3. Vista general y tipos de datos

"""

display(df.info())

quality_summary = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "missing_count": df.isna().sum(),
    "missing_pct": (df.isna().mean() * 100).round(2),
    "unique_values": df.nunique(dropna=True),
})

display(quality_summary)

"""## 4. Limpieza ligera y feature engineering

"""

df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

price_columns = ["Open", "High", "Low", "Close", "Adj Close"]
numeric_columns = price_columns + ["Volume"]

for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")

df = df.sort_values("Date").reset_index(drop=True)

df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Month Name"] = df["Date"].dt.month_name()
df["Quarter"] = df["Date"].dt.quarter
df["Day of Week"] = df["Date"].dt.day_name()

df["Daily Return"] = df["Adj Close"].pct_change()
df["Log Return"] = np.log(df["Adj Close"] / df["Adj Close"].shift(1))
df["Intraday Return"] = (df["Close"] - df["Open"]) / df["Open"]
df["High Low Spread"] = df["High"] - df["Low"]
df["High Low Spread Pct"] = df["High Low Spread"] / df["Open"]
df["Close Open Spread"] = df["Close"] - df["Open"]

df["MA 20"] = df["Adj Close"].rolling(window=20).mean()
df["MA 50"] = df["Adj Close"].rolling(window=50).mean()
df["MA 200"] = df["Adj Close"].rolling(window=200).mean()
df["Rolling Volatility 20"] = df["Daily Return"].rolling(window=20).std() * np.sqrt(252)
df["Rolling Volatility 60"] = df["Daily Return"].rolling(window=60).std() * np.sqrt(252)

df["Cumulative Return"] = (1 + df["Daily Return"].fillna(0)).cumprod() - 1
df["Cumulative Max"] = df["Adj Close"].cummax()
df["Drawdown"] = df["Adj Close"] / df["Cumulative Max"] - 1

display(df.head())
display(df.tail())

"""## 5. Validaciones de calidad

"""

post_cleaning_quality = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "missing_count": df.isna().sum(),
    "missing_pct": (df.isna().mean() * 100).round(2),
    "unique_values": df.nunique(dropna=True),
})

duplicate_full_rows = df.duplicated().sum()
duplicate_dates = df["Date"].duplicated().sum()
date_min = df["Date"].min()
date_max = df["Date"].max()
calendar_days = (date_max - date_min).days

invalid_ohlc = df[
    (df["High"] < df[["Open", "Close", "Low"]].max(axis=1)) |
    (df["Low"] > df[["Open", "Close", "High"]].min(axis=1)) |
    (df["Volume"] < 0)
]

print(f"Duplicados exactos: {duplicate_full_rows}")
print(f"Fechas duplicadas: {duplicate_dates}")
print(f"Fecha mínima: {date_min.date()}")
print(f"Fecha máxima: {date_max.date()}")
print(f"Días calendario cubiertos: {calendar_days:,}")
print(f"Registros con inconsistencias OHLC/volumen: {len(invalid_ohlc):,}")

display(post_cleaning_quality.sort_values(["missing_count", "unique_values"], ascending=[False, True]))
display(invalid_ohlc.head())

"""## 6. Estadística descriptiva

"""

analysis_numeric_columns = [
    "Open",
    "High",
    "Low",
    "Close",
    "Adj Close",
    "Volume",
    "Daily Return",
    "Log Return",
    "Intraday Return",
    "High Low Spread Pct",
    "Rolling Volatility 20",
    "Rolling Volatility 60",
    "Cumulative Return",
    "Drawdown",
]

display(df[analysis_numeric_columns].describe(percentiles=[0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]).T.round(6))

annual_summary = (
    df.groupby("Year", observed=True)
    .agg(
        trading_days=("Date", "count"),
        first_adj_close=("Adj Close", "first"),
        last_adj_close=("Adj Close", "last"),
        avg_volume=("Volume", "mean"),
        min_drawdown=("Drawdown", "min"),
        avg_daily_return=("Daily Return", "mean"),
        volatility=("Daily Return", "std"),
    )
    .assign(
        annual_return=lambda data: data["last_adj_close"] / data["first_adj_close"] - 1,
        annualized_volatility=lambda data: data["volatility"] * np.sqrt(252),
    )
    .round(6)
)

display(annual_summary.tail(15))

"""## 7. Distribución temporal

"""

trading_days_by_year = df.groupby("Year", observed=True).size()

plt.figure(figsize=(14, 5))
sns.barplot(x=trading_days_by_year.index, y=trading_days_by_year.values, color="#3b82f6")
plt.title("Registros por año")
plt.xlabel("Año")
plt.ylabel("Días de trading")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

display(trading_days_by_year.to_frame("trading_days").T)

"""## 8. Distribución de variables numéricas

"""

distribution_columns = ["Adj Close", "Volume", "Daily Return", "Log Return", "Intraday Return", "High Low Spread Pct"]

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()

for ax, column in zip(axes, distribution_columns):
    sns.histplot(data=df, x=column, kde=True, ax=ax, color="#2563eb")
    ax.set_title(column)
    ax.set_xlabel("")

plt.suptitle("Distribuciones numéricas", fontsize=16, fontweight="bold", y=1.02)
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()

for ax, column in zip(axes, distribution_columns):
    sns.boxplot(data=df, x=column, ax=ax, color="#93c5fd")
    ax.set_title(column)
    ax.set_xlabel("")

plt.suptitle("Boxplots para detección visual de outliers", fontsize=16, fontweight="bold", y=1.02)
plt.tight_layout()
plt.show()

"""## 9. Correlaciones entre variables numéricas

"""

correlation_columns = [
    "Open",
    "High",
    "Low",
    "Close",
    "Adj Close",
    "Volume",
    "Daily Return",
    "Intraday Return",
    "High Low Spread Pct",
    "Rolling Volatility 20",
    "Drawdown",
]

correlation_matrix = df[correlation_columns].corr(method="pearson")

plt.figure(figsize=(12, 9))
sns.heatmap(
    correlation_matrix,
    annot=True,
    fmt=".2f",
    cmap="vlag",
    center=0,
    square=True,
    linewidths=0.5,
)
plt.title("Matriz de correlación")
plt.tight_layout()
plt.show()

correlation_pairs = (
    correlation_matrix.where(np.triu(np.ones(correlation_matrix.shape), k=1).astype(bool))
    .stack()
    .sort_values(key=lambda values: values.abs(), ascending=False)
)

display(correlation_pairs.head(20).to_frame("correlation"))

"""## 10. Precio, volumen y medias móviles

"""

plt.figure(figsize=(16, 7))
plt.plot(df["Date"], df["Adj Close"], label="Adj Close", linewidth=1.5)
plt.plot(df["Date"], df["MA 50"], label="MA 50", linewidth=1.2)
plt.plot(df["Date"], df["MA 200"], label="MA 200", linewidth=1.2)
plt.title("NVDA - Precio ajustado y medias móviles")
plt.xlabel("Fecha")
plt.ylabel("Precio ajustado")
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(16, 5))
plt.plot(df["Date"], df["Volume"], color="#64748b", linewidth=0.8)
plt.title("NVDA - Volumen diario")
plt.xlabel("Fecha")
plt.ylabel("Volumen")
plt.tight_layout()
plt.show()

recent_window = df.tail(756).copy()

plt.figure(figsize=(16, 7))
plt.plot(recent_window["Date"], recent_window["Adj Close"], label="Adj Close", linewidth=1.5)
plt.plot(recent_window["Date"], recent_window["MA 20"], label="MA 20", linewidth=1.2)
plt.plot(recent_window["Date"], recent_window["MA 50"], label="MA 50", linewidth=1.2)
plt.plot(recent_window["Date"], recent_window["MA 200"], label="MA 200", linewidth=1.2)
plt.title("NVDA - Últimos 3 años aproximados")
plt.xlabel("Fecha")
plt.ylabel("Precio ajustado")
plt.legend()
plt.tight_layout()
plt.show()

"""## 11. Retornos y volatilidad

"""

fig, axes = plt.subplots(3, 1, figsize=(16, 12), sharex=True)

axes[0].plot(df["Date"], df["Daily Return"], color="#2563eb", linewidth=0.7)
axes[0].axhline(0, color="black", linewidth=0.8)
axes[0].set_title("Retorno diario")

axes[1].plot(df["Date"], df["Rolling Volatility 20"], color="#ef4444", linewidth=1.0, label="20 días")
axes[1].plot(df["Date"], df["Rolling Volatility 60"], color="#f97316", linewidth=1.0, label="60 días")
axes[1].set_title("Volatilidad anualizada móvil")
axes[1].legend()

axes[2].plot(df["Date"], df["Cumulative Return"], color="#16a34a", linewidth=1.2)
axes[2].set_title("Retorno acumulado")
axes[2].set_xlabel("Fecha")

plt.tight_layout()
plt.show()

return_summary = pd.DataFrame({
    "metric": [
        "daily_return_mean",
        "daily_return_median",
        "daily_return_std",
        "annualized_return_mean",
        "annualized_volatility",
        "positive_days_pct",
        "negative_days_pct",
    ],
    "value": [
        df["Daily Return"].mean(),
        df["Daily Return"].median(),
        df["Daily Return"].std(),
        df["Daily Return"].mean() * 252,
        df["Daily Return"].std() * np.sqrt(252),
        df["Daily Return"].gt(0).mean(),
        df["Daily Return"].lt(0).mean(),
    ],
})

display(return_summary)

"""## 12. Drawdown y mejores/peores días

"""

plt.figure(figsize=(16, 5))
plt.fill_between(df["Date"], df["Drawdown"], 0, color="#ef4444", alpha=0.35)
plt.plot(df["Date"], df["Drawdown"], color="#991b1b", linewidth=0.8)
plt.title("NVDA - Drawdown histórico")
plt.xlabel("Fecha")
plt.ylabel("Drawdown")
plt.tight_layout()
plt.show()

top_positive_days = df.nlargest(10, "Daily Return")[["Date", "Adj Close", "Daily Return", "Volume"]]
top_negative_days = df.nsmallest(10, "Daily Return")[["Date", "Adj Close", "Daily Return", "Volume"]]
max_drawdown_row = df.loc[df["Drawdown"].idxmin(), ["Date", "Adj Close", "Drawdown"]]

print("Máximo drawdown:")
display(max_drawdown_row.to_frame().T)

print("Mejores 10 días por retorno diario:")
display(top_positive_days)

print("Peores 10 días por retorno diario:")
display(top_negative_days)

"""## 13. Análisis mensual y anual

"""

monthly_df = (
    df.set_index("Date")
    .resample("ME")
    .agg(
        first_adj_close=("Adj Close", "first"),
        last_adj_close=("Adj Close", "last"),
        avg_volume=("Volume", "mean"),
        trading_days=("Adj Close", "count"),
        monthly_volatility=("Daily Return", "std"),
    )
    .assign(monthly_return=lambda data: data["last_adj_close"] / data["first_adj_close"] - 1)
)

monthly_df["year"] = monthly_df.index.year
monthly_df["month"] = monthly_df.index.month

monthly_return_pivot = monthly_df.pivot(index="year", columns="month", values="monthly_return")

plt.figure(figsize=(13, 10))
sns.heatmap(monthly_return_pivot, cmap="RdYlGn", center=0, annot=False, linewidths=0.3)
plt.title("Retornos mensuales")
plt.xlabel("Mes")
plt.ylabel("Año")
plt.tight_layout()
plt.show()

display(monthly_df.tail(24).round(6))
display(annual_summary.sort_values("annual_return", ascending=False).head(10))
display(annual_summary.sort_values("annual_return", ascending=True).head(10))

"""## 14. Detección programática de outliers

"""

def iqr_outlier_summary(data: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    rows = []

    for column in columns:
        clean_series = data[column].dropna()
        q1 = clean_series.quantile(0.25)
        q3 = clean_series.quantile(0.75)
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        outlier_mask = data[column].lt(lower_bound) | data[column].gt(upper_bound)

        rows.append({
            "column": column,
            "q1": q1,
            "q3": q3,
            "iqr": iqr,
            "lower_bound": lower_bound,
            "upper_bound": upper_bound,
            "outlier_count": int(outlier_mask.sum()),
            "outlier_pct": round(outlier_mask.mean() * 100, 2),
        })

    return pd.DataFrame(rows).sort_values("outlier_count", ascending=False)

outlier_columns = ["Daily Return", "Log Return", "Intraday Return", "High Low Spread Pct", "Volume", "Rolling Volatility 20"]
outlier_summary = iqr_outlier_summary(df, outlier_columns)

display(outlier_summary)

extreme_return_days = df[
    df["Daily Return"].abs() >= df["Daily Return"].abs().quantile(0.99)
][["Date", "Open", "High", "Low", "Close", "Adj Close", "Volume", "Daily Return"]]

display(extreme_return_days.sort_values("Daily Return"))

"""## 15. Dataset analítico final

"""

analysis_df = df.copy()

display(analysis_df.head())
display(analysis_df.tail())
print(f"Shape final: {analysis_df.shape}")